### ISSUE TITLE
Cross: Setup base Terraform

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#2]
**Acceptance Criteria**
1. AS A developer I WANT to navigate to the Cross-functional-requirements repository and find a directory that contains the terraform files SO THAT I can view the IAC/Terraform files AND be able to edit those files SO THAT I can update the infrastructure
2. AS A developer I WANT to navigate to the Cross-functional-requirements repository and find a directory (.github/workflows) that contains IAC deployment pipeline files (Github actions) SO THAT I can view the pipeline process AND be able to edit those files SO THAT I can update the pipeline process
3. AS A developer I WANT to be able to navigate to the Cross-functional-requirements repository and run the IAC/Terraform pipeline (Github actions) which will deploy the resources specified in the terraform files to Azure 
4. AS A developer I WANT to navigate to the Cross-functional-requirements repository and find a directory that contains the terraform files and editing the resources detailed in those files will trigger the terraform pipeline SO THAT I can edit the system infrastructure  

**Tasks**
- [x] Create terraform file structure anatomy e.g. main.tf, variables.tf
- [x] Reference resource group in terraform files
- [x] Create some mock/sample resources as test in terraform files 
- [x] Create pipeline to build terraform files and deploy infra
