### ISSUE TITLE
Cross: Create Milestone list for MVP

### ISSUE THREAD

**Issue by shelabd** [buerokratt/Cross-functional-requirements#37]
As a DMR project member
I WANT to be able to refer back to a document outlining the milestones of an MVP
SO THAT I have a priority as to the work that needs to be done

### Acceptance Criteria

- [x] Setup discussion on expected flow
- [x] Basic End to End chat flow expectations decided
- [x] Basic registration expectations decided 
- [x] DevOps definition for MVP decided
